"""
Usage:
# This script is to give the command lines for using pytorch-ssd

#This is for Jetson Object Detection. I moved all jpeg and xml from movie to labelImg folders under train and test to save. 
# run xml_to_csv.py in Tensorflow/scripts/preprocessing subdirectory to create train data csv label:
python xml_to_csv2.py \
-i /Users/craig/Documents/src/pytorch-ssd-ON-NX/data/open_images/train \
-o /Users/craig/Documents/src/pytorch-ssd-ON-NX/data/open_images/sub-train-annotations-bbox.csv


# run xml_to_csv.py in Tensorflow/scripts/preprocessing subdirectory to create test data csv label:
python xml_to_csv2.py \
-i /Users/craig/Documents/src/pytorch-ssd-ON-NX/data/open_images/test \
-o /Users/craig/Documents/src/pytorch-ssd-ON-NX/data/open_images/sub-test-annotations-bbox.csv

# run xml_to_csv.py in Tensorflow/scripts/preprocessing subdirectory to create test data csv label:
python xml_to_csv2.py \
-i /Users/craig/Documents/src/pytorch-ssd-ON-NX/data/open_images/validation \
-o /Users/craig/Documents/src/pytorch-ssd-ON-NX/data/open_images/sub-validation-annotations-bbox.csv


"""

import os
import glob
import pandas as pd
import argparse
import xml.etree.ElementTree as ET


def xml_to_csv(path):
    """Iterates through all .xml files (generated by labelImg) in a given directory and combines them in a single Pandas datagrame.

    Parameters:
    ----------
    path : {str}
        The path containing the .xml files
    Returns
    -------
    Pandas DataFrame
        The produced dataframe
    """

    xml_list = []
    for xml_file in glob.glob(path + '/*.xml'):
        tree = ET.parse(xml_file)
        root = tree.getroot()
        for member in root.findall('object'):
            value = (root.find('filename').text,     #ImageID
                    int(root.find('size')[0].text),  #Width
                    int(root.find('size')[1].text),  #Height
                    int(member[4][0].text),          #Xmin
                    int(member[4][2].text),          #Xmax
                    int(member[4][1].text),          #Ymin
                    int(member[4][3].text),          #Ymax
                    member[0].text                   #ClassName                    
                    )
            xml_list.append(value)
    column_name = ['ImageID', 'width', 'height',
                   'Xmin', 'Xmax', 'Ymin', 'Ymax' , 'ClassName']
    xml_df = pd.DataFrame(xml_list, columns=column_name)
    return xml_df


def main():
    # Initiate argument parser
    parser = argparse.ArgumentParser(
        description="Sample TensorFlow XML-to-CSV converter")
    parser.add_argument("-i",
                        "--inputDir",
                        help="Path to the folder where the input .xml files are stored",
                        type=str)
    parser.add_argument("-o",
                        "--outputFile",
                        help="Name of output .csv file (including path)", type=str)
    args = parser.parse_args()

    if(args.inputDir is None):
        args.inputDir = os.getcwd()
    if(args.outputFile is None):
        args.outputFile = args.inputDir + "/labels.csv"

    assert(os.path.isdir(args.inputDir))

    xml_df = xml_to_csv(args.inputDir)
    xml_df.to_csv(
        args.outputFile, index=None)
    print('Successfully converted xml to csv.')


if __name__ == '__main__':
    main()
